### PR TITLE
add BIDS conversion script

### PR DESCRIPTION
**Pull request by loj**
I've created a BIDS conversion script based off of BEP003 and BEP001.

### CODE REVIEW

**Comment by mih** [comment]
Awesome, thx! Can you please tune this script a little -- following the spirit of https://github.com/datalad-datasets/hcp-structural-preprocessed/commit/b36379c00cd8995b86405556ad484bbe3b4e3759

The goal is to be able to run it repeatedly, and be able to re-BIDSify future (partial) updates. IN particular to be able to pick up on individual changed files.

Thx in advance!

**Comment by loj** [comment]
Done. :-) The script is updated to reflect the changes in [datalad-datasets/hcp-structural-preprocessed@b36379c](https://github.com/datalad-datasets/hcp-structural-preprocessed/commit/b36379c00cd8995b86405556ad484bbe3b4e3759)

**Comment by adswa** [comment]
Sorry to have missed them in the first assembling, but now the dataset also contains the 7T data that you found. :-)

**Comment by loj** [comment]
No worries. :-) I'll adjust the script to include the 7T data. Thanks for adding the additional data!

**Comment by loj** [comment]
The script is now adjusted to include the 7T diffusion data.

**Comment by adswa** [comment]
This PR looks like we forgot about it, but its still useful - is there anything that speaks against merging this?

**Comment by loj** [comment]
Hah, indeed! I completely forgot about this. I would say go for it. :-)

**Pull request merged**
